language: node_js

node_js:
#  - "0.12"
#  - "4.0"
#  - "4"
  - "5"
  - "5.5"
  - "stable"

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run lint
  - npm test
#  - npm run bithound check git@github.com:chrisslater/snapperfish.git
#  - npm run test-node
