export const SUBMIT_CONTACT_FORM = 'SUBMIT_CONTACT_FORM';
export const SUBMIT_CONTACT_FORM_LOADING = 'SUBMIT_CONTACT_FORM_LOADING';
export const SUBMIT_CONTACT_FORM_SUCCEEDED = 'SUBMIT_CONTACT_FORM_SUCCEEDED';
export const SUBMIT_CONTACT_FORM_FAILED = 'SUBMIT_CONTACT_FORM_FAILED';
